apiVersion: v2
name: stalwart
description: Helm chart for the Stalwart mail and collaboration server
type: application
version: 0.2.1
appVersion: "v0.16.8"
home: https://stalw.art
icon: https://stalw.art/img/logo.svg
sources:
  - https://github.com/stalwartlabs/stalwart
  - https://stalw.art/docs/cluster/orchestration/kubernetes/
  - https://github.com/kgrubb/stalwart-helm-chart
maintainers:
  - name: kgrubb
    email: 8471701+kgrubb@users.noreply.github.com
    url: https://github.com/kgrubb
keywords:
  - mail
  - smtp
  - imap
  - jmap
  - stalwart
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/kgrubb/stalwart-helm-chart/issues
    - name: source
      url: https://github.com/kgrubb/stalwart-helm-chart
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/signKey: |
    fingerprint: AFB495384FDAD4EDC0EBF8FECA999A73395F45FD
    url: https://kgrubb.github.io/stalwart-helm-chart/public.key
