name: Sync Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: azure/setup-helm@v5

      - name: Sync gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x scripts/sync-gh-pages.sh
          ./scripts/sync-gh-pages.sh full
